<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>clone</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <OptimizationPreference>Size</OptimizationPreference>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StackTraceSupport>false</StackTraceSupport>
    <AppleMinOSVersion>14.0</AppleMinOSVersion>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Clone.Git/Clone.Git.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <NativeArchitecture Condition="'$(NativeArchitecture)' == ''">arm64</NativeArchitecture>
  </PropertyGroup>
  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <DirectPInvoke Include="clone_native" />
    <NativeLibrary Include="../artifacts/native/$(NativeArchitecture)/libclone_native.a" />
  </ItemGroup>
  <Target Name="BuildTargetNativeArchive" BeforeTargets="LinkNative" Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <MSBuild Projects="../Clone.Git/Clone.Git.csproj" Targets="BuildMacInterop" Properties="NativeArchitecture=$(NativeArchitecture)" />
  </Target>
</Project>
